name: e_commerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  flutter_screenutil: ^5.5.4
  video_player: ^2.4.10
  flutter_svg: ^1.1.5
  widget_mask: ^1.0.0+0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/videos/
    - assets/icons/
    - assets/images/



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/plus_jakarta_display/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/plus_jakarta_display/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/plus_jakarta_display/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/plus_jakarta_display/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/plus_jakarta_display/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/plus_jakarta_display/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/plus_jakarta_display/PlusJakartaSans-ExtraLight.ttf
          weight: 200
    - family: Grafita
      fonts:
        - asset: fonts/grafita/Slava Antipov - Grafita Normal DEMO.ttf
          weight: 400
        - asset: fonts/grafita/Slava Antipov - Grafita Normal.ttf
          weight: 500
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
